#!/usr/bin/env python3
"""Generate corpus/documents/api-reference.md.

The large fixture is generated rather than hand-written so it stays long enough
to be a real small-context test (~600 lines) without being 600 lines of
hand-maintained prose. Regenerate with:

    python3 corpus/tools/gen-api-reference.py

Output is deterministic: no randomness, no timestamps. Regenerating must
produce a byte-identical file, so an accidental diff means someone edited the
fixture by hand instead of editing this generator.
"""

import pathlib

MODULES = [
    ("Accounts", "accounts", [
        ("list", "GET", "/v1/accounts", "List accounts visible to the caller."),
        ("get", "GET", "/v1/accounts/{id}", "Fetch a single account by id."),
        ("create", "POST", "/v1/accounts", "Create a new account."),
        ("update", "PATCH", "/v1/accounts/{id}", "Update mutable account fields."),
        ("delete", "DELETE", "/v1/accounts/{id}", "Soft-delete an account."),
    ]),
    ("Projects", "projects", [
        ("list", "GET", "/v1/projects", "List projects within an account."),
        ("get", "GET", "/v1/projects/{id}", "Fetch a single project."),
        ("create", "POST", "/v1/projects", "Create a project."),
        ("archive", "POST", "/v1/projects/{id}/archive", "Archive a project."),
    ]),
    ("Deployments", "deployments", [
        ("list", "GET", "/v1/deployments", "List deployments for a project."),
        ("get", "GET", "/v1/deployments/{id}", "Fetch a deployment."),
        ("create", "POST", "/v1/deployments", "Trigger a deployment."),
        ("cancel", "POST", "/v1/deployments/{id}/cancel", "Cancel a running deployment."),
        ("logs", "GET", "/v1/deployments/{id}/logs", "Stream deployment logs."),
    ]),
    ("Secrets", "secrets", [
        ("list", "GET", "/v1/secrets", "List secret names, never values."),
        ("set", "PUT", "/v1/secrets/{name}", "Create or replace a secret."),
        ("delete", "DELETE", "/v1/secrets/{name}", "Remove a secret."),
    ]),
    ("Webhooks", "webhooks", [
        ("list", "GET", "/v1/webhooks", "List configured webhooks."),
        ("create", "POST", "/v1/webhooks", "Register a webhook endpoint."),
        ("test", "POST", "/v1/webhooks/{id}/test", "Send a test payload."),
        ("delete", "DELETE", "/v1/webhooks/{id}", "Remove a webhook."),
    ]),
]

PARAMS = {
    "list": [
        ("`limit`", "integer", "no", "`20`", "Page size, 1–100."),
        ("`cursor`", "string", "no", "—", "Opaque pagination cursor."),
        ("`order`", "string", "no", "`created`", "Sort field."),
    ],
    "get": [
        ("`id`", "string", "yes", "—", "Resource identifier."),
        ("`expand`", "string[]", "no", "—", "Related objects to inline."),
    ],
    "create": [
        ("`name`", "string", "yes", "—", "Human-readable name."),
        ("`metadata`", "object", "no", "`{}`", "Arbitrary key/value pairs."),
        ("`idempotency_key`", "string", "no", "—", "Safe-retry token."),
    ],
    "update": [
        ("`id`", "string", "yes", "—", "Resource identifier."),
        ("`name`", "string", "no", "—", "New name."),
    ],
    "delete": [
        ("`id`", "string", "yes", "—", "Resource identifier."),
        ("`force`", "boolean", "no", "`false`", "Skip the soft-delete window."),
    ],
}
DEFAULT_PARAMS = [
    ("`id`", "string", "yes", "—", "Resource identifier."),
]

ERRORS = [
    ("400", "`invalid_request`", "A parameter failed validation."),
    ("401", "`unauthenticated`", "Missing or expired credentials."),
    ("403", "`forbidden`", "The caller lacks permission."),
    ("404", "`not_found`", "No such resource, or it is not visible."),
    ("409", "`conflict`", "The resource is in an incompatible state."),
    ("429", "`rate_limited`", "Too many requests; retry after the header value."),
]


def table(headers, rows):
    """Emit an aligned GFM table — matching the dominant style in the corpus."""
    cols = list(zip(*([headers] + rows))) if rows else [[h] for h in headers]
    widths = [max(len(c) for c in col) for col in cols]
    out = ["| " + " | ".join(h.ljust(w) for h, w in zip(headers, widths)) + " |",
           "| " + " | ".join("-" * w for w in widths) + " |"]
    for row in rows:
        out.append("| " + " | ".join(c.ljust(w) for c, w in zip(row, widths)) + " |")
    return out


L = []
L += [
    "# API reference",
    "",
    "Purpose in the corpus: the large-document fixture. This file is long enough",
    "that a small model cannot hold it in context, which is exactly the condition",
    "acceptance criterion 9.1 tests — locate and edit one row without reading the",
    "document.",
    "",
    "Generated by `corpus/tools/gen-api-reference.py`. Do not edit by hand; edit",
    "the generator and regenerate.",
    "",
    "Representative benchmark tasks against this file:",
    "",
    "- change the default of `limit` in *Accounts > list > Parameters* to `50`",
    "- add a `409` row to one endpoint's error table",
    "- add an endpoint subsection in the correct alphabetical position",
    "- rename a parameter across one module only, not document-wide",
    "",
    "## Conventions",
    "",
    "- All requests require a bearer token in the `Authorization` header.",
    "- All timestamps are RFC 3339 in UTC.",
    "- All list endpoints are cursor-paginated.",
    "- Unknown request fields are rejected rather than ignored.",
    "",
    "### Common headers",
    "",
]
L += table(
    ["Header", "Required", "Description"],
    [
        ("`Authorization`", "yes", "`Bearer <token>`"),
        ("`Content-Type`", "on write", "Must be `application/json`."),
        ("`Idempotency-Key`", "no", "Deduplicates retried writes."),
        ("`X-Request-Id`", "no", "Echoed back for correlation."),
    ],
)
L += [
    "",
    "### Rate limits",
    "",
]
L += table(
    ["Tier", "Requests/min", "Burst", "Notes"],
    [
        ("free", "60", "100", "Shared pool per account."),
        ("pro", "600", "1000", "Per API key."),
        ("enterprise", "6000", "10000", "Negotiated."),
    ],
)
L += [""]

for module, slug, endpoints in MODULES:
    L += [
        f"## {module}",
        "",
        f"Operations on {slug}. All paths are relative to the API root.",
        "",
    ]
    L += table(
        ["Operation", "Method", "Path", "Summary"],
        [(f"`{n}`", m, f"`{p}`", s) for n, m, p, s in endpoints],
    )
    L += [""]

    for name, method, path, summary in endpoints:
        L += [
            f"### {name}",
            "",
            summary,
            "",
            "```http",
            f"{method} {path}",
            "```",
            "",
            "#### Parameters",
            "",
        ]
        L += table(
            ["Name", "Type", "Required", "Default", "Description"],
            [list(r) for r in PARAMS.get(name, DEFAULT_PARAMS)],
        )
        L += [
            "",
            "#### Errors",
            "",
        ]
        L += table(["Status", "Code", "Meaning"], [list(r) for r in ERRORS])
        L += [
            "",
            "#### Example",
            "",
            "```bash",
            f"curl -X {method} \\",
            f"  https://api.example.com{path} \\",
            '  -H "Authorization: Bearer $TOKEN"',
            "```",
            "",
        ]

L += [
    "## Changelog",
    "",
    "- `2026-08-14` — added `Deployments.cancel`.",
    "- `2026-07-02` — `Secrets.list` no longer returns values.",
    "- `2026-05-19` — cursor pagination replaced offset pagination.",
    "",
]

out = pathlib.Path(__file__).resolve().parent.parent / "documents" / "api-reference.md"
out.write_text("\n".join(L))
print(f"wrote {out} ({len(L)} lines)")
